fastlane_version "1.110.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    # carthage
  end

  ## PRIVATE LANES ##

  private_lane :commit do |options|
    build = Actions.lane_context[Actions::SharedValues::BUILD_NUMBER]
    commit_version_bump(
      message: "Build #{build}",
      xcodeproj: "nbro.xcodeproj"
    )
  end

  ## PUBLIC LANES ##

  desc "fetch all certificates and provisioning profiles"
  lane :codesigning do |options|
    ["development", "adhoc", "appstore"].each do |type|
      match(
        type: type
      )
    end
  end

  desc "bump version"
  lane :bump do
    ensure_git_status_clean
    increment_build_number
    commit
   end
   
  desc "testflight"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "appstore"
  lane :release do
    gym(scheme: 'nbro')
    deliver(force: true)
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end
