fastlane_version "1.51.0"
default_platform :ios


platform :ios do

  ############################## PRE ##############################

  before_all do
  end

  ######################### PRIVATE LANES #########################

  private_lane :build do |options|
    gym(
      scheme: "nbro",
      clean: true,
      include_bitcode: false,
      workspace: "nbro.xcworkspace",
      output_directory: "../",
      output_name: "nbro.ipa",
      xcargs: "ARCHIVE=YES" # Used to tell the Fabric run script to upload dSYM file
    )
  end

  private_lane :commit do |options|
    build = Actions.lane_context[Actions::SharedValues::BUILD_NUMBER]
    commit_version_bump(
      message: "Build #{build}"
    )
  end

  ######################### PUBLIC LANES ##########################

  desc "Increment build number"
  lane :bump do
    ensure_git_status_clean
    increment_build_number
    commit
  end

  desc "Publish to iTunes Connect"
  lane :itc do
    ensure_git_status_clean
    cocoapods
    increment_build_number
    build
    pilot(
      ipa: "../nbro.ipa",
      skip_submission: true,
    )
    commit
  end

  ############################# POST ##############################

  after_all do |lane|
  end

  error do |lane, exception|
  end
end
